version: "3.9"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: scrapper
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  web:
    build:
      context: ./webscrapper
      dockerfile: Dockerfile
    command: 
        sh -c "python manage.py migrate && gunicorn webscrapper.wsgi:application --bind 0.0.0.0:8000"
    volumes:
    - ./webscrapper:/app   # 👈 correct this
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=scrapper
      - DB_USER=postgres
      - DB_PASSWORD=12345678

  frontend:
    build:
      context: ./web-scraper-dashboard
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

volumes:
  postgres_data:
