# Generated by Django 5.2 on 2025-05-24 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CrawlJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=100, unique=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('urls', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=50)),
                ('product_url', models.URLField(unique=True)),
                ('image_url', models.URLField()),
                ('details', models.JSONField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='app.category')),
                ('crawl_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.crawljob')),
            ],
        ),
        migrations.CreateModel(
            name='ProductChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('new', 'New'), ('updated', 'Updated'), ('removed', 'Removed')], max_length=10)),
                ('product_url', models.URLField()),
                ('data', models.JSONField()),
                ('crawl_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.crawljob')),
            ],
        ),
    ]
