# Generated by Django 5.2 on 2025-06-12 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='url',
            field=models.URLField(max_length=2000, unique=True),
        ),
        migrations.AlterField(
            model_name='crawljob',
            name='job_id',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.URLField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_url',
            field=models.URLField(max_length=2000, unique=True),
        ),
        migrations.AlterField(
            model_name='productchangelog',
            name='product_url',
            field=models.URLField(max_length=2000),
        ),
    ]
