# Generated by Django 5.2 on 2025-06-13 19:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_category_url_alter_crawljob_job_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='change_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
