// Sample data matching your actual API structure
export const sampleRealComparisonData = {
  new: [
    {
      name: "Adidas x Korn Track Pant",
      price: "109.00",
      product_url: "https://wonderjackets.com/product/adidas-x-korn-track-pant/",
      image_url: "https://picsum.photos/id/1011/400/400",
      details: {
        "Image URL": "https://wonderjackets.com/wp-content/uploads/2024/08/Adidas-x-Korn-Track-Pant.webp",
        "Thumbnail Images": ["https://picsum.photos/id/1011/100/100", "https://picsum.photos/id/1012/100/100"],
        Title: "Adidas x Korn Track Pant",
        Rating: null,
        "Customer Reviews": null,
        "Size Options": ["Choose an option", "Female", "Male"],
        "Product Specification": [
          "Material: Polyester",
          "Inner: Soft Lining",
          "Pockets: Two Side Pockets",
          "Color: Black",
        ],
        "Previous Price": "$109.00",
        "New Price": "$49.00",
        "Price Range": ["$0.00", "$109.00", "$49.00", "$299.00", "$199.00", "$279.00", "$289.00", "$399.00"],
      },
      category: "https://wonderjackets.com/",
      change_date: "2025-06-13T23:59:59.000000Z",
    },
    {
      name: "Nike Air Force 1 Jacket",
      price: "89.99",
      product_url: "https://wonderjackets.com/product/nike-air-force-1-jacket/",
      image_url: "https://picsum.photos/id/1025/400/400",
      details: {
        "Image URL": "https://wonderjackets.com/wp-content/uploads/2024/08/Nike-Air-Force-1-Jacket.webp",
        "Thumbnail Images": [
          "https://picsum.photos/id/1025/100/100",
          "https://picsum.photos/id/1026/100/100",
          "https://picsum.photos/id/1027/100/100",
        ],
        Title: "Nike Air Force 1 Jacket",
        Rating: "4.5",
        "Customer Reviews": "23",
        "Size Options": ["Choose an option", "S", "M", "L", "XL"],
        "Product Specification": [
          "Material: Cotton Blend",
          "Inner: Fleece Lining",
          "Pockets: Four Pockets",
          "Color: White/Black",
        ],
        "Previous Price": "$129.99",
        "New Price": "$89.99",
        "Price Range": ["$89.99", "$99.99", "$109.99"],
      },
      category: "https://wonderjackets.com/",
      change_date: "2025-06-14T10:30:00.000000Z",
    },
  ],
  updated: [
    {
      name: "Adidas x Korn Track Pant",
      price: "49.00",
      product_url: "https://wonderjackets.com/product/adidas-x-korn-track-pant/",
      image_url: "https://picsum.photos/id/1011/400/400",
      details: {
        "Image URL": "https://wonderjackets.com/wp-content/uploads/2024/08/Adidas-x-Korn-Track-Pant.webp",
        "Thumbnail Images": [
          "https://picsum.photos/id/1011/100/100",
          "https://picsum.photos/id/1012/100/100",
          "https://picsum.photos/id/1013/100/100",
        ],
        Title: "Adidas x Korn Track Pant - Limited Edition",
        Rating: "4.2",
        "Customer Reviews": "15",
        "Size Options": ["Choose an option", "XS", "S", "M", "L", "XL", "XXL"],
        "Product Specification": [
          "Material: Premium Polyester",
          "Inner: Soft Mesh Lining",
          "Pockets: Two Side Pockets with Zippers",
          "Color: Black with Korn Logo",
          "Care: Machine Washable",
        ],
        "Previous Price": "$109.00",
        "New Price": "$49.00",
        "Price Range": ["$49.00", "$59.00", "$69.00", "$79.00"],
      },
      category: "https://wonderjackets.com/",
      changes: {
        price: {
          old: "109.00",
          old_date: "2025-06-10T12:00:00.000000Z",
          new: "49.00",
          change_date: "2025-06-13T23:59:59.000000Z",
        },
        details: {
          old: {
            "Image URL": "https://wonderjackets.com/wp-content/uploads/2024/08/Adidas-x-Korn-Track-Pant.webp",
            "Thumbnail Images": ["https://picsum.photos/id/1011/100/100"],
            Title: "Adidas x Korn Track Pant",
            Rating: null,
            "Customer Reviews": null,
            "Size Options": ["Choose an option", "Female", "Male"],
            "Product Specification": [
              "Material: Polyester",
              "Inner: Soft Lining",
              "Pockets: Two Side Pockets",
              "Color: Black",
            ],
            "Previous Price": "$109.00",
            "New Price": "$109.00",
            "Price Range": ["$109.00", "$119.00"],
          },
          old_date: "2025-06-10T12:00:00.000000Z",
          new: {
            "Image URL": "https://wonderjackets.com/wp-content/uploads/2024/08/Adidas-x-Korn-Track-Pant.webp",
            "Thumbnail Images": [
              "https://picsum.photos/id/1011/100/100",
              "https://picsum.photos/id/1012/100/100",
              "https://picsum.photos/id/1013/100/100",
            ],
            Title: "Adidas x Korn Track Pant - Limited Edition",
            Rating: "4.2",
            "Customer Reviews": "15",
          },
          change_date: "2025-06-13T23:59:59.000000Z",
        },
      },
      change_date: "2025-06-13T23:59:59.000000Z",
    },
    {
      name: "Supreme Box Logo Hoodie",
      price: "299.99",
      product_url: "https://wonderjackets.com/product/supreme-box-logo-hoodie/",
      image_url: "https://picsum.photos/id/1059/400/400",
      details: {
        "Image URL": "https://wonderjackets.com/wp-content/uploads/2024/08/Supreme-Box-Logo-Hoodie.webp",
        "Thumbnail Images": [
          "https://picsum.photos/id/1059/100/100",
          "https://picsum.photos/id/1060/100/100",
          "https://picsum.photos/id/1061/100/100",
          "https://picsum.photos/id/1062/100/100",
        ],
        Title: "Supreme Box Logo Hoodie - Red",
        Rating: "4.8",
        "Customer Reviews": "87",
        "Size Options": ["Choose an option", "S", "M", "L", "XL"],
        "Product Specification": [
          "Material: 100% Cotton",
          "Inner: Fleece Lining",
          "Pockets: Kangaroo Pocket",
          "Color: Red",
          "Fit: Regular",
          "Care: Machine Wash Cold",
        ],
        "Previous Price": "$399.99",
        "New Price": "$299.99",
        "Price Range": ["$299.99", "$349.99", "$399.99"],
      },
      category: "https://wonderjackets.com/",
      changes: {
        price: {
          old: "399.99",
          old_date: "2025-06-08T15:30:00.000000Z",
          new: "299.99",
          change_date: "2025-06-14T09:15:00.000000Z",
        },
        details: {
          old: {
            Title: "Supreme Box Logo Hoodie",
            Rating: "4.6",
            "Customer Reviews": "72",
            "Size Options": ["Choose an option", "M", "L", "XL"],
            "Product Specification": [
              "Material: Cotton Blend",
              "Inner: Fleece Lining",
              "Pockets: Kangaroo Pocket",
              "Color: Red",
            ],
            "Previous Price": "$399.99",
            "New Price": "$399.99",
            "Price Range": ["$399.99", "$449.99"],
            "Thumbnail Images": ["https://picsum.photos/id/1059/100/100", "https://picsum.photos/id/1060/100/100"],
          },
          old_date: "2025-06-08T15:30:00.000000Z",
          new: {
            Title: "Supreme Box Logo Hoodie - Red",
            Rating: "4.8",
            "Customer Reviews": "87",
            "Size Options": ["Choose an option", "S", "M", "L", "XL"],
            "Product Specification": [
              "Material: 100% Cotton",
              "Inner: Fleece Lining",
              "Pockets: Kangaroo Pocket",
              "Color: Red",
              "Fit: Regular",
              "Care: Machine Wash Cold",
            ],
            "Thumbnail Images": [
              "https://picsum.photos/id/1059/100/100",
              "https://picsum.photos/id/1060/100/100",
              "https://picsum.photos/id/1061/100/100",
              "https://picsum.photos/id/1062/100/100",
            ],
          },
          change_date: "2025-06-14T09:15:00.000000Z",
        },
      },
      change_date: "2025-06-14T09:15:00.000000Z",
    },
    {
      name: "Vintage Denim Jacket",
      price: "79.99",
      product_url: "https://wonderjackets.com/product/vintage-denim-jacket/",
      image_url: "https://picsum.photos/id/1066/400/400",
      details: {
        "Image URL": "https://wonderjackets.com/wp-content/uploads/2024/08/Vintage-Denim-Jacket.webp",
        "Thumbnail Images": ["https://picsum.photos/id/1066/100/100", "https://picsum.photos/id/1067/100/100"],
        Title: "Vintage Stonewashed Denim Jacket",
        Rating: "4.3",
        "Customer Reviews": "31",
        "Size Options": ["Choose an option", "XS", "S", "M", "L", "XL", "XXL"],
        "Product Specification": [
          "Material: 100% Cotton Denim",
          "Inner: Unlined",
          "Pockets: Two Chest Pockets, Two Side Pockets",
          "Color: Blue Stonewashed",
          "Style: Vintage Cut",
        ],
        "Previous Price": "$59.99",
        "New Price": "$79.99",
        "Price Range": ["$79.99", "$89.99"],
      },
      category: "https://wonderjackets.com/",
      changes: {
        price: {
          old: "59.99",
          old_date: "2025-06-12T08:45:00.000000Z",
          new: "79.99",
          change_date: "2025-06-14T14:20:00.000000Z",
        },
        details: {
          old: {
            Title: "Classic Denim Jacket",
            Rating: "4.1",
            "Customer Reviews": "25",
            "Size Options": ["Choose an option", "S", "M", "L", "XL"],
            "Product Specification": [
              "Material: Cotton Denim",
              "Inner: Unlined",
              "Pockets: Two Chest Pockets",
              "Color: Blue",
            ],
            "Previous Price": "$59.99",
            "New Price": "$59.99",
            "Price Range": ["$59.99"],
            "Thumbnail Images": ["https://picsum.photos/id/1066/100/100"],
          },
          old_date: "2025-06-12T08:45:00.000000Z",
          new: {
            Title: "Vintage Stonewashed Denim Jacket",
            Rating: "4.3",
            "Customer Reviews": "31",
            "Size Options": ["Choose an option", "XS", "S", "M", "L", "XL", "XXL"],
            "Product Specification": [
              "Material: 100% Cotton Denim",
              "Inner: Unlined",
              "Pockets: Two Chest Pockets, Two Side Pockets",
              "Color: Blue Stonewashed",
              "Style: Vintage Cut",
            ],
            "Thumbnail Images": ["https://picsum.photos/id/1066/100/100", "https://picsum.photos/id/1067/100/100"],
          },
          change_date: "2025-06-14T14:20:00.000000Z",
        },
      },
      change_date: "2025-06-14T14:20:00.000000Z",
    },
  ],
  removed: [
    {
      name: "Adidas Old Jacket",
      price: "99.00",
      product_url: "https://wonderjackets.com/product/adidas-old-jacket/",
      image_url: "https://picsum.photos/id/1069/400/400",
      details: {
        Title: "Adidas Classic Track Jacket",
        Rating: "4.5",
        "Customer Reviews": "42",
        "Size Options": ["Choose an option", "M", "L", "XL"],
        "Product Specification": [
          "Material: Polyester",
          "Inner: Mesh Lining",
          "Pockets: Two Side Pockets",
          "Color: Navy Blue",
        ],
        "Previous Price": "$99.00",
        "New Price": "$99.00",
        "Price Range": ["$99.00", "$109.00"],
      },
      category: "https://wonderjackets.com/",
      change_date: "2025-06-13T23:59:59.000000Z",
    },
  ],
}
